export { default as Head} from './head/Head';
export { default as Hero} from './hero/Hero';
export { default as About} from './about/About';
export { default as Resume} from './Resume/Resume';
export { default as Skills} from './skills/Skills';
export { default as Projects} from './projects/Projects';
export { default as Awards} from './awards/Awards';
export { default as Contact} from './contact/Contact';
export { default as Footer} from './footer/Footer';